name: BridgingAnalyzer
main: sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
version: '${project.version}'
authors: [ SakuraKooi, CatMoe ]
commands:
  bridge:
    description: Bridging Analyzer Config
    usage: /bridge
  clearblock:
    description: clear placed block
    usage: /clearblock
  imstuck:
    description: destroy near block
    usage: /imstuck
  genvillager:
    description: create villager spawn point
    usage: /genvillager
  bsaveworld:
    description: save the world
    usage: /bsaveworld
permissions:
  bridginganalyzer.noclear:
    default: op
  bridginganalyzer.clear:
    default: op
  bridginganalyzer.admin:
    default: op